# the name of the current app
spring:
  application:
    name: spring-boot-web-demo

  # indent the returned JSON responses
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: aVeryComplexPassword
    data: data-h2.sql
    schema: schema-h2.sql
    initialize: false

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true

# logging settings
logging:
  level:
    root: info
    org.apache: warn
    org.springframework: warn
    org.hibernate: warn

  pattern:
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'